/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PxVec3Wrapper : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PxVec3Wrapper(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PxVec3Wrapper obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PxVec3Wrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CGePhysicsPINVOKE.delete_PxVec3Wrapper(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public double x {
    set {
      CGePhysicsPINVOKE.PxVec3Wrapper_x_set(swigCPtr, value);
    } 
    get {
      double ret = CGePhysicsPINVOKE.PxVec3Wrapper_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      CGePhysicsPINVOKE.PxVec3Wrapper_y_set(swigCPtr, value);
    } 
    get {
      double ret = CGePhysicsPINVOKE.PxVec3Wrapper_y_get(swigCPtr);
      return ret;
    } 
  }

  public double z {
    set {
      CGePhysicsPINVOKE.PxVec3Wrapper_z_set(swigCPtr, value);
    } 
    get {
      double ret = CGePhysicsPINVOKE.PxVec3Wrapper_z_get(swigCPtr);
      return ret;
    } 
  }

  public PxVec3Wrapper() : this(CGePhysicsPINVOKE.new_PxVec3Wrapper__SWIG_0(), true) {
  }

  public PxVec3Wrapper(double nx, double ny, double nz) : this(CGePhysicsPINVOKE.new_PxVec3Wrapper__SWIG_1(nx, ny, nz), true) {
  }

}
