/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CGePhysX : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CGePhysX(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CGePhysX obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CGePhysX() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CGePhysicsPINVOKE.delete_CGePhysX(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CGePhysX() : this(CGePhysicsPINVOKE.new_CGePhysX(), true) {
  }

  public void OnInit() {
    CGePhysicsPINVOKE.CGePhysX_OnInit(swigCPtr);
  }

  public void StepPhysX(float stepTime) {
    CGePhysicsPINVOKE.CGePhysX_StepPhysX(swigCPtr, stepTime);
  }

  public void createCloth(string clothName, SWIGTYPE_p_physx__PxReal clothScale, SWIGTYPE_p_physx__PxVec3 clothOffset, SWIGTYPE_p_physx__PxQuat clothRotate) {
    CGePhysicsPINVOKE.CGePhysX_createCloth__SWIG_0(swigCPtr, clothName, SWIGTYPE_p_physx__PxReal.getCPtr(clothScale), SWIGTYPE_p_physx__PxVec3.getCPtr(clothOffset), SWIGTYPE_p_physx__PxQuat.getCPtr(clothRotate));
    if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void createCloth(string clothName, SWIGTYPE_p_physx__PxReal clothScale, SWIGTYPE_p_physx__PxVec3 clothOffset) {
    CGePhysicsPINVOKE.CGePhysX_createCloth__SWIG_1(swigCPtr, clothName, SWIGTYPE_p_physx__PxReal.getCPtr(clothScale), SWIGTYPE_p_physx__PxVec3.getCPtr(clothOffset));
    if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void createCloth(string clothName, SWIGTYPE_p_physx__PxReal clothScale) {
    CGePhysicsPINVOKE.CGePhysX_createCloth__SWIG_2(swigCPtr, clothName, SWIGTYPE_p_physx__PxReal.getCPtr(clothScale));
    if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void createCloth(string clothName) {
    CGePhysicsPINVOKE.CGePhysX_createCloth__SWIG_3(swigCPtr, clothName);
  }

  public bool addCollisionSpheres(SWIGTYPE_p_vectorT_physx__PxVec3_t positions, SWIGTYPE_p_vectorT_physx__PxReal_t radius, SWIGTYPE_p_vectorT_physx__PxU32_t indexPair) {
    bool ret = CGePhysicsPINVOKE.CGePhysX_addCollisionSpheres(swigCPtr, SWIGTYPE_p_vectorT_physx__PxVec3_t.getCPtr(positions), SWIGTYPE_p_vectorT_physx__PxReal_t.getCPtr(radius), SWIGTYPE_p_vectorT_physx__PxU32_t.getCPtr(indexPair));
    if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void updateCollisionSpheres(SWIGTYPE_p_vectorT_physx__PxVec3_t positions) {
    CGePhysicsPINVOKE.CGePhysX_updateCollisionSpheres(swigCPtr, SWIGTYPE_p_vectorT_physx__PxVec3_t.getCPtr(positions));
    if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getClothIndices(SWIGTYPE_p_p_physx__PxU32 indices, SWIGTYPE_p_physx__PxU32 nIndices) {
    bool ret = CGePhysicsPINVOKE.CGePhysX_getClothIndices(swigCPtr, SWIGTYPE_p_p_physx__PxU32.getCPtr(indices), SWIGTYPE_p_physx__PxU32.getCPtr(nIndices));
    if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getClothParticles(SWIGTYPE_p_physx__PxVec3 particles) {
    bool ret = CGePhysicsPINVOKE.CGePhysX_getClothParticles(swigCPtr, SWIGTYPE_p_physx__PxVec3.getCPtr(particles));
    return ret;
  }

  public void Destroy() {
    CGePhysicsPINVOKE.CGePhysX_Destroy(swigCPtr);
  }

  public SWIGTYPE_p_physx__PxCloth mCloth {
    set {
      CGePhysicsPINVOKE.CGePhysX_mCloth_set(swigCPtr, SWIGTYPE_p_physx__PxCloth.getCPtr(value));
    } 
    get {
      IntPtr cPtr = CGePhysicsPINVOKE.CGePhysX_mCloth_get(swigCPtr);
      SWIGTYPE_p_physx__PxCloth ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_physx__PxCloth(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_physx__PxU32_t mClothIndices {
    set {
      CGePhysicsPINVOKE.CGePhysX_mClothIndices_set(swigCPtr, SWIGTYPE_p_vectorT_physx__PxU32_t.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_physx__PxU32_t ret = new SWIGTYPE_p_vectorT_physx__PxU32_t(CGePhysicsPINVOKE.CGePhysX_mClothIndices_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_physx__PxVec3_t mClothVertices {
    set {
      CGePhysicsPINVOKE.CGePhysX_mClothVertices_set(swigCPtr, SWIGTYPE_p_vectorT_physx__PxVec3_t.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_physx__PxVec3_t ret = new SWIGTYPE_p_vectorT_physx__PxVec3_t(CGePhysicsPINVOKE.CGePhysX_mClothVertices_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_physx__PxClothCollisionData mClothCollisionData {
    set {
      CGePhysicsPINVOKE.CGePhysX_mClothCollisionData_set(swigCPtr, SWIGTYPE_p_physx__PxClothCollisionData.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_physx__PxClothCollisionData ret = new SWIGTYPE_p_physx__PxClothCollisionData(CGePhysicsPINVOKE.CGePhysX_mClothCollisionData_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_physx__PxClothCollisionSphere_t mClothCollisionSpheres {
    set {
      CGePhysicsPINVOKE.CGePhysX_mClothCollisionSpheres_set(swigCPtr, SWIGTYPE_p_vectorT_physx__PxClothCollisionSphere_t.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_physx__PxClothCollisionSphere_t ret = new SWIGTYPE_p_vectorT_physx__PxClothCollisionSphere_t(CGePhysicsPINVOKE.CGePhysX_mClothCollisionSpheres_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_physx__PxU32_t mClothCollisionSpheresIndexPair {
    set {
      CGePhysicsPINVOKE.CGePhysX_mClothCollisionSpheresIndexPair_set(swigCPtr, SWIGTYPE_p_vectorT_physx__PxU32_t.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_physx__PxU32_t ret = new SWIGTYPE_p_vectorT_physx__PxU32_t(CGePhysicsPINVOKE.CGePhysX_mClothCollisionSpheresIndexPair_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_physx__PxU32_t mClothCollisionIndexPair {
    set {
      CGePhysicsPINVOKE.CGePhysX_mClothCollisionIndexPair_set(swigCPtr, SWIGTYPE_p_vectorT_physx__PxU32_t.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_physx__PxU32_t ret = new SWIGTYPE_p_vectorT_physx__PxU32_t(CGePhysicsPINVOKE.CGePhysX_mClothCollisionIndexPair_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_physx__PxReal mCharacterScale {
    set {
      CGePhysicsPINVOKE.CGePhysX_mCharacterScale_set(swigCPtr, SWIGTYPE_p_physx__PxReal.getCPtr(value));
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_physx__PxReal ret = new SWIGTYPE_p_physx__PxReal(CGePhysicsPINVOKE.CGePhysX_mCharacterScale_get(swigCPtr), true);
      if (CGePhysicsPINVOKE.SWIGPendingException.Pending) throw CGePhysicsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_physx__PxPhysics getPhysics() {
    IntPtr cPtr = CGePhysicsPINVOKE.CGePhysX_getPhysics(swigCPtr);
    SWIGTYPE_p_physx__PxPhysics ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_physx__PxPhysics(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_physx__PxScene getScene() {
    IntPtr cPtr = CGePhysicsPINVOKE.CGePhysX_getScene(swigCPtr);
    SWIGTYPE_p_physx__PxScene ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_physx__PxScene(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_physx__PxCooking getCooking() {
    IntPtr cPtr = CGePhysicsPINVOKE.CGePhysX_getCooking(swigCPtr);
    SWIGTYPE_p_physx__PxCooking ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_physx__PxCooking(cPtr, false);
    return ret;
  }

}
