/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class CGePhysicsPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("CGePhysics", EntryPoint="SWIGRegisterExceptionCallbacks_CGePhysics")]
    public static extern void SWIGRegisterExceptionCallbacks_CGePhysics(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("CGePhysics", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_CGePhysics")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_CGePhysics(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_CGePhysics(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_CGePhysics(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(CGePhysicsPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(CGePhysicsPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("CGePhysics", EntryPoint="SWIGRegisterStringCallback_CGePhysics")]
    public static extern void SWIGRegisterStringCallback_CGePhysics(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_CGePhysics(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static CGePhysicsPINVOKE() {
  }


  [DllImport("CGePhysics", EntryPoint="CSharp_new_CGePhysX")]
  public static extern IntPtr new_CGePhysX();

  [DllImport("CGePhysics", EntryPoint="CSharp_delete_CGePhysX")]
  public static extern void delete_CGePhysX(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_OnInit")]
  public static extern void CGePhysX_OnInit(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_StepPhysX")]
  public static extern void CGePhysX_StepPhysX(HandleRef jarg1, float jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_createCloth__SWIG_0")]
  public static extern void CGePhysX_createCloth__SWIG_0(HandleRef jarg1, string jarg2, HandleRef jarg3, HandleRef jarg4, HandleRef jarg5);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_createCloth__SWIG_1")]
  public static extern void CGePhysX_createCloth__SWIG_1(HandleRef jarg1, string jarg2, HandleRef jarg3, HandleRef jarg4);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_createCloth__SWIG_2")]
  public static extern void CGePhysX_createCloth__SWIG_2(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_createCloth__SWIG_3")]
  public static extern void CGePhysX_createCloth__SWIG_3(HandleRef jarg1, string jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_addCollisionSpheres")]
  public static extern bool CGePhysX_addCollisionSpheres(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_updateCollisionSpheres")]
  public static extern void CGePhysX_updateCollisionSpheres(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_getClothIndices")]
  public static extern bool CGePhysX_getClothIndices(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_getClothParticles")]
  public static extern bool CGePhysX_getClothParticles(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_Destroy")]
  public static extern void CGePhysX_Destroy(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mCloth_set")]
  public static extern void CGePhysX_mCloth_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mCloth_get")]
  public static extern IntPtr CGePhysX_mCloth_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothIndices_set")]
  public static extern void CGePhysX_mClothIndices_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothIndices_get")]
  public static extern IntPtr CGePhysX_mClothIndices_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothVertices_set")]
  public static extern void CGePhysX_mClothVertices_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothVertices_get")]
  public static extern IntPtr CGePhysX_mClothVertices_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionData_set")]
  public static extern void CGePhysX_mClothCollisionData_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionData_get")]
  public static extern IntPtr CGePhysX_mClothCollisionData_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionSpheres_set")]
  public static extern void CGePhysX_mClothCollisionSpheres_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionSpheres_get")]
  public static extern IntPtr CGePhysX_mClothCollisionSpheres_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionSpheresIndexPair_set")]
  public static extern void CGePhysX_mClothCollisionSpheresIndexPair_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionSpheresIndexPair_get")]
  public static extern IntPtr CGePhysX_mClothCollisionSpheresIndexPair_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionIndexPair_set")]
  public static extern void CGePhysX_mClothCollisionIndexPair_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mClothCollisionIndexPair_get")]
  public static extern IntPtr CGePhysX_mClothCollisionIndexPair_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mCharacterScale_set")]
  public static extern void CGePhysX_mCharacterScale_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_mCharacterScale_get")]
  public static extern IntPtr CGePhysX_mCharacterScale_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_getPhysics")]
  public static extern IntPtr CGePhysX_getPhysics(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_getScene")]
  public static extern IntPtr CGePhysX_getScene(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_CGePhysX_getCooking")]
  public static extern IntPtr CGePhysX_getCooking(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_delete_Shape")]
  public static extern void delete_Shape(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_x_set")]
  public static extern void Shape_x_set(HandleRef jarg1, double jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_x_get")]
  public static extern double Shape_x_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_y_set")]
  public static extern void Shape_y_set(HandleRef jarg1, double jarg2);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_y_get")]
  public static extern double Shape_y_get(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_move")]
  public static extern void Shape_move(HandleRef jarg1, double jarg2, double jarg3);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_area")]
  public static extern double Shape_area(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_perimeter")]
  public static extern double Shape_perimeter(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_nshapes_set")]
  public static extern void Shape_nshapes_set(int jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Shape_nshapes_get")]
  public static extern int Shape_nshapes_get();

  [DllImport("CGePhysics", EntryPoint="CSharp_new_Circle")]
  public static extern IntPtr new_Circle(double jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Circle_area")]
  public static extern double Circle_area(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Circle_perimeter")]
  public static extern double Circle_perimeter(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_delete_Circle")]
  public static extern void delete_Circle(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_new_Square")]
  public static extern IntPtr new_Square(double jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Square_area")]
  public static extern double Square_area(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Square_perimeter")]
  public static extern double Square_perimeter(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_delete_Square")]
  public static extern void delete_Square(HandleRef jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Circle_SWIGUpcast")]
  public static extern IntPtr Circle_SWIGUpcast(IntPtr jarg1);

  [DllImport("CGePhysics", EntryPoint="CSharp_Square_SWIGUpcast")]
  public static extern IntPtr Square_SWIGUpcast(IntPtr jarg1);
}
