/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Circle : Shape {
  private HandleRef swigCPtr;

  internal Circle(IntPtr cPtr, bool cMemoryOwn) : base(CGePhysicsPINVOKE.Circle_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Circle obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Circle() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CGePhysicsPINVOKE.delete_Circle(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Circle(double r) : this(CGePhysicsPINVOKE.new_Circle(r), true) {
  }

  public override double area() {
    double ret = CGePhysicsPINVOKE.Circle_area(swigCPtr);
    return ret;
  }

  public override double perimeter() {
    double ret = CGePhysicsPINVOKE.Circle_perimeter(swigCPtr);
    return ret;
  }

}
